import { useEffect, useState } from 'react';
import { Target, RefreshCw, Save, Building2, Gauge, CalendarDays } from 'lucide-react';
import dashboardOperatingService from '../../services/dashboardOperatingService';
import NstPageHero from '../../components/system/NstPageHero';

const today = () => new Date(Date.now() - new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const money = (value, type) => type === 'sales_quantity' ? new Intl.NumberFormat('en-US').format(Number(value||0)) : `৳${new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(value||0))}`;

export default function DashboardTargetsPage() {
  const [date,setDate]=useState(today()); const [type,setType]=useState('sales_amount'); const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const res=await dashboardOperatingService.targets({date,target_type:type});setData(res?.data?.data||null)}catch(e){setError(e?.response?.data?.message||'Targets could not load.')}finally{setLoading(false)}};
  useEffect(()=>{load()},[date,type]);
  const updateBranch=(id,value)=>setData((current)=>({...current,branches:current.branches.map((row)=>row.branch_id===id?{...row,target_value:value}:row)}));
  const save=async()=>{if(!data?.can_manage)return;setSaving(true);setError('');try{const res=await dashboardOperatingService.saveTargets({date,target_type:type,combined_mode:data.combined.combined_mode,combined_target:data.combined.target_value,branch_targets:data.branches.map((row)=>({branch_id:row.branch_id,target_value:Number(row.target_value||0)}))});setData(res?.data?.data||data)}catch(e){setError(e?.response?.data?.message||'Targets could not save.')}finally{setSaving(false)}};
  return <main className="min-h-full bg-[var(--nst-dashboard-bg)] p-4 text-[var(--nst-dashboard-text)] md:p-6"><div className="mx-auto max-w-[1500px] space-y-5"><NstPageHero pageKey="/dashboard-targets" icon={Target} defaults={{ eyebrow:'Real Database Targets', title:"Today's Target", subtitle:'Branch-wise targets plus a separate Manual or Auto Combined Target.' }} actions={<div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 rounded-xl border border-[var(--nst-dashboard-border)] px-3"><CalendarDays size={16}/><input type="date" value={date} onChange={(e)=>setDate(e.target.value)} className="bg-transparent py-3 outline-none"/></label><select value={type} onChange={(e)=>setType(e.target.value)} className="rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] px-3 text-sm font-bold"><option value="sales_amount">Sales Amount</option><option value="sales_quantity">Sales Quantity</option><option value="profit">Profit</option><option value="collection">Collection</option><option value="purchase">Purchase</option></select><button onClick={load} className="rounded-xl border border-[var(--nst-dashboard-border)] p-3"><RefreshCw className={loading?'animate-spin':''} size={17}/></button>{data?.can_manage&&<button onClick={save} disabled={saving} className="flex items-center gap-2 rounded-xl bg-[var(--nst-dashboard-primary)] px-4 py-3 text-sm font-black text-white"><Save size={17}/>{saving?'Saving...':'Save Targets'}</button>}</div>}/>{error&&<div className="rounded-2xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm font-bold text-rose-500">{error}</div>}
  {data&&<><section className="rounded-[28px] border border-[var(--nst-dashboard-primary)] bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_9%,var(--nst-dashboard-surface))] p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><Gauge size={24}/><div><h2 className="text-xl font-black">All Branches / Combined</h2><p className="text-xs text-[var(--nst-dashboard-muted)]">Actual is calculated from all visible branch transactions without double counting.</p></div></div>{data.can_manage&&<select value={data.combined.combined_mode} onChange={(e)=>setData({...data,combined:{...data.combined,combined_mode:e.target.value}})} className="rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-3 text-sm font-bold"><option value="manual">Manual Combined Target</option><option value="auto_total">Auto Total of Branch Targets</option></select>}</div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat label="Target" value={data.combined.combined_mode==='manual'&&data.can_manage?<input type="number" min="0" value={data.combined.target_value} onChange={(e)=>setData({...data,combined:{...data.combined,target_value:e.target.value}})} className="w-full bg-transparent text-xl font-black outline-none"/>:money(data.combined.target_value,type)}/><Stat label="Achieved" value={money(data.combined.actual_value,type)}/><Stat label="Remaining" value={money(data.combined.remaining_value,type)}/><Stat label="Completion" value={`${data.combined.percentage}%`}/></div></section>
  <div className="grid gap-4 lg:grid-cols-2">{data.branches.map((row)=><section key={row.branch_id} className="rounded-[26px] border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-5 shadow-[var(--nst-dashboard-shadow)]"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_14%,transparent)] text-[var(--nst-dashboard-primary)]"><Building2 size={19}/></span><div><h3 className="font-black">{row.branch_name}</h3><p className="text-[10px] text-[var(--nst-dashboard-muted)]">Refreshed {new Date(row.last_refreshed_at).toLocaleTimeString('en-BD')}</p></div></div><span className={`rounded-full px-3 py-1 text-[10px] font-black ${row.status==='achieved'?'bg-emerald-500/10 text-emerald-500':'bg-amber-500/10 text-amber-500'}`}>{row.status.replaceAll('_',' ')}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-[var(--nst-dashboard-bg)] p-3"><span className="text-xs text-[var(--nst-dashboard-muted)]">Target</span>{data.can_manage?<input type="number" min="0" value={row.target_value} onChange={(e)=>updateBranch(row.branch_id,e.target.value)} className="mt-1 block w-full bg-transparent text-lg font-black outline-none"/>:<strong className="mt-1 block text-lg">{money(row.target_value,type)}</strong>}</div><div className="rounded-xl bg-[var(--nst-dashboard-bg)] p-3"><span className="text-xs text-[var(--nst-dashboard-muted)]">Achieved</span><strong className="mt-1 block text-lg">{money(row.actual_value,type)}</strong></div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-[var(--nst-dashboard-bg)]"><span className="block h-full rounded-full bg-[var(--nst-dashboard-primary)]" style={{width:`${Math.min(100,row.percentage)}%`}}/></div><div className="mt-2 flex justify-between text-xs font-bold"><span>{row.percentage}%</span><span>Remaining {money(row.remaining_value,type)}</span></div></section>)}</div></>}
  {!data&&loading&&<div className="grid min-h-[420px] place-items-center"><RefreshCw className="animate-spin" size={38}/></div>}</div></main>;
}
function Stat({label,value}){return <div className="rounded-2xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-4"><p className="text-xs font-bold text-[var(--nst-dashboard-muted)]">{label}</p><div className="mt-1 text-xl font-black">{value}</div></div>}
