import { useCallback, useEffect, useMemo, useState } from 'react';
import { BadgeDollarSign, CheckCircle2, Download, FileClock, HeartHandshake, Loader2, MailPlus, Plus, RefreshCw, Save, ShieldCheck, Target, TicketCheck, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import { localDateString } from '../../utils/localDate';

const MONEY = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 2 });
const money = (value) => MONEY.format(Number(value || 0));
const unwrap = (response) => response?.data?.data ?? response?.data ?? {};
const today = () => localDateString();

function Metric({ label, value, note, icon: Icon = ShieldCheck }) {
  return <article className="rounded-3xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-5 shadow-[var(--nst-dashboard-shadow)]"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[var(--nst-dashboard-muted)]">{label}</p><p className="mt-2 text-2xl font-black text-[var(--nst-dashboard-text)]">{value}</p>{note && <p className="mt-1 text-xs text-[var(--nst-dashboard-muted)]">{note}</p>}</div><span className="rounded-2xl bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_14%,transparent)] p-3 text-[var(--nst-dashboard-primary)]"><Icon size={20}/></span></div></article>;
}
function Panel({ title, description, action, children }) {
  return <section className="rounded-3xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-5 shadow-[var(--nst-dashboard-shadow)]"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-black text-[var(--nst-dashboard-text)]">{title}</h2>{description && <p className="mt-1 text-sm text-[var(--nst-dashboard-muted)]">{description}</p>}</div>{action}</div>{children}</section>;
}
function Table({ columns, rows = [], empty = 'No live CRM records found.' }) {
  if (!rows.length) return <div className="rounded-2xl border border-dashed border-[var(--nst-dashboard-border)] p-8 text-center text-sm text-[var(--nst-dashboard-muted)]">{empty}</div>;
  return <div className="overflow-x-auto rounded-2xl border border-[var(--nst-dashboard-border)]"><table className="min-w-full text-left text-sm"><thead className="bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_8%,transparent)] text-xs uppercase text-[var(--nst-dashboard-muted)]"><tr>{columns.map(c => <th key={c.key} className="whitespace-nowrap px-4 py-3 font-black">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-[var(--nst-dashboard-border)]">{rows.map((row, index) => <tr key={row.id ?? index} className="hover:bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_5%,transparent)]">{columns.map(c => <td key={c.key} className="whitespace-nowrap px-4 py-3 text-[var(--nst-dashboard-text)]">{c.render ? c.render(row) : (row[c.key] ?? '-')}</td>)}</tr>)}</tbody></table></div>;
}
function Input({ label, ...props }) { return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<input {...props} className="mt-1.5 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]"/></label>; }
function Select({ label, children, ...props }) { return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<select {...props} className="mt-1.5 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]">{children}</select></label>; }
function Textarea({ label, ...props }) { return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<textarea {...props} className="mt-1.5 min-h-28 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]"/></label>; }
function Button({ children, busy, tone = 'primary', ...props }) { const tones = { primary: 'bg-[var(--nst-dashboard-primary)] text-white', soft: 'bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_12%,transparent)] text-[var(--nst-dashboard-primary)]', danger: 'bg-red-500/10 text-red-500' }; return <button type="button" {...props} disabled={busy || props.disabled} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 ${tones[tone]}`}>{busy ? <Loader2 size={16} className="animate-spin"/> : null}{children}</button>; }

export default function CrmStage6Center({ refreshToken }) {
  const [overview,setOverview]=useState({}); const [ref,setRef]=useState({}); const [customers,setCustomers]=useState([]); const [leads,setLeads]=useState([]); const [activities,setActivities]=useState([]); const [support,setSupport]=useState([]); const [segments,setSegments]=useState([]); const [campaigns,setCampaigns]=useState([]); const [logs,setLogs]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [lead,setLead]=useState({name:'',phone:'',email:'',interest:'',estimated_value:'',priority:'normal',source:'manual',next_follow_up_at:''});
  const [caseForm,setCaseForm]=useState({customer_id:'',lead_id:'',subject:'',category:'general',priority:'normal',description:'',due_at:''});
  const [segment,setSegment]=useState({name:'',code:'',field:'loyalty_points_min',value:'1500'});
  const [campaign,setCampaign]=useState({name:'',channel:'manual',segment_id:'',subject:'',message:'',scheduled_at:''});
  const [activity,setActivity]=useState({customer_id:'',lead_id:'',activity_type:'follow_up',subject:'',details:'',due_at:today(),status:'planned'});
  const load = useCallback(async()=>{ setLoading(true); try{ const [o,r,c,l,a,s,se,ca,h]=await Promise.all([api.get('/crm/overview'),api.get('/crm/reference-data'),api.get('/crm/customers'),api.get('/crm/leads'),api.get('/crm/activities'),api.get('/crm/support-cases'),api.get('/crm/segments'),api.get('/crm/campaigns'),api.get('/crm/audit-history')]); setOverview(unwrap(o)); setRef(unwrap(r)); setCustomers(unwrap(c)||[]); setLeads(unwrap(l)||[]); setActivities(unwrap(a)||[]); setSupport(unwrap(s)||[]); setSegments(unwrap(se)||[]); setCampaigns(unwrap(ca)||[]); setLogs(unwrap(h)?.logs||[]); }catch(e){ toast.error(e?.response?.data?.message || 'CRM data load failed.'); } finally{ setLoading(false); } },[]);
  useEffect(()=>{ load(); },[load,refreshToken]);
  const customerOptions = useMemo(()=>customers.slice(0,200),[customers]); const leadOptions = useMemo(()=>leads.slice(0,200),[leads]);
  const saveLead=async()=>{ if(!lead.name)return toast.error('Lead name is required.'); setSaving(true); try{ await api.post('/crm/leads',{...lead,estimated_value:Number(lead.estimated_value||0),next_follow_up_at:lead.next_follow_up_at||null}); toast.success('Lead created.'); setLead({name:'',phone:'',email:'',interest:'',estimated_value:'',priority:'normal',source:'manual',next_follow_up_at:''}); load(); }catch(e){ toast.error(e?.response?.data?.message||'Lead save failed.'); }finally{ setSaving(false); } };
  const convertLead=async(id)=>{ setSaving(true); try{ await api.post(`/crm/leads/${id}/convert`,{create_customer:true,segment:'Converted Lead',note:'Converted from CRM Center'}); toast.success('Lead converted to customer.'); load(); }catch(e){ toast.error(e?.response?.data?.message||'Lead conversion failed.'); }finally{ setSaving(false); } };
  const saveCase=async()=>{ if(!caseForm.subject)return toast.error('Support subject is required.'); setSaving(true); try{ await api.post('/crm/support-cases',{...caseForm,customer_id:caseForm.customer_id?Number(caseForm.customer_id):null,lead_id:caseForm.lead_id?Number(caseForm.lead_id):null,due_at:caseForm.due_at||null}); toast.success('Support case created.'); setCaseForm({customer_id:'',lead_id:'',subject:'',category:'general',priority:'normal',description:'',due_at:''}); load(); }catch(e){ toast.error(e?.response?.data?.message||'Support case save failed.'); }finally{ setSaving(false); } };
  const saveActivity=async()=>{ if(!activity.subject)return toast.error('Activity subject is required.'); setSaving(true); try{ await api.post('/crm/activities',{...activity,customer_id:activity.customer_id?Number(activity.customer_id):null,lead_id:activity.lead_id?Number(activity.lead_id):null,due_at:activity.due_at||null}); toast.success('Activity saved.'); setActivity({customer_id:'',lead_id:'',activity_type:'follow_up',subject:'',details:'',due_at:today(),status:'planned'}); load(); }catch(e){ toast.error(e?.response?.data?.message||'Activity save failed.'); }finally{ setSaving(false); } };
  const saveSegment=async()=>{ if(!segment.name||!segment.code)return toast.error('Segment name and code are required.'); setSaving(true); try{ await api.post('/crm/segments',{name:segment.name,code:segment.code,rules:[{field:segment.field,operator:segment.field==='loyalty_points_min'?'>':'=',value:segment.field==='loyalty_points_min'?Number(segment.value||0):segment.value}],is_dynamic:true,is_active:true}); toast.success('Segment saved.'); setSegment({name:'',code:'',field:'loyalty_points_min',value:'1500'}); load(); }catch(e){ toast.error(e?.response?.data?.message||'Segment save failed.'); }finally{ setSaving(false); } };
  const saveCampaign=async()=>{ if(!campaign.name||!campaign.message)return toast.error('Campaign name and message are required.'); setSaving(true); try{ await api.post('/crm/campaigns',{...campaign,segment_id:campaign.segment_id?Number(campaign.segment_id):null,scheduled_at:campaign.scheduled_at||null}); toast.success('Campaign draft saved.'); setCampaign({name:'',channel:'manual',segment_id:'',subject:'',message:'',scheduled_at:''}); load(); }catch(e){ toast.error(e?.response?.data?.message||'Campaign save failed.'); }finally{ setSaving(false); } };
  const launchCampaign=async(id)=>{ setSaving(true); try{ await api.post(`/crm/campaigns/${id}/launch`); toast.success('Campaign audience queued.'); load(); }catch(e){ toast.error(e?.response?.data?.message||'Campaign launch failed.'); }finally{ setSaving(false); } };
  const s=overview.summary||{}; const acceptance=overview.acceptance||{};
  return <div className="space-y-5">{loading && <div className="flex items-center gap-2 text-sm text-[var(--nst-dashboard-muted)]"><Loader2 className="animate-spin" size={16}/>Loading live CRM data…</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Customers" value={Number(s.customers||0).toLocaleString()} icon={Users}/><Metric label="Active Leads" value={s.active_leads||0} icon={HeartHandshake}/><Metric label="Won Value" value={money(s.won_value)} icon={BadgeDollarSign}/><Metric label="Open Support" value={s.open_support_tickets||0} icon={TicketCheck}/></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1fr]"><Panel title="Lead Pipeline & Conversion" description="Create real leads, track follow-ups, and convert won leads into customer profiles."><div className="grid gap-3 sm:grid-cols-2"><Input label="Lead Name" value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})}/><Input label="Phone" value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})}/><Input label="Email" type="email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/><Input label="Estimated Value" type="number" min="0" value={lead.estimated_value} onChange={e=>setLead({...lead,estimated_value:e.target.value})}/><Select label="Priority" value={lead.priority} onChange={e=>setLead({...lead,priority:e.target.value})}>{(ref.priorities||['low','normal','high','urgent']).map(x=><option key={x} value={x}>{x}</option>)}</Select><Input label="Next Follow-up" type="datetime-local" value={lead.next_follow_up_at} onChange={e=>setLead({...lead,next_follow_up_at:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Product / Service Interest" value={lead.interest} onChange={e=>setLead({...lead,interest:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveLead}><Plus size={16}/>Create Lead</Button></div></Panel>
      <Panel title="Support Case SLA" description="Create CRM support cases against a customer or lead and track priority/status."><div className="grid gap-3 sm:grid-cols-2"><Select label="Customer" value={caseForm.customer_id} onChange={e=>setCaseForm({...caseForm,customer_id:e.target.value,lead_id:''})}><option value="">Select customer</option>{customerOptions.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</Select><Select label="Lead" value={caseForm.lead_id} onChange={e=>setCaseForm({...caseForm,lead_id:e.target.value,customer_id:''})}><option value="">Select lead</option>{leadOptions.map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone||l.stage}</option>)}</Select><Input label="Subject" value={caseForm.subject} onChange={e=>setCaseForm({...caseForm,subject:e.target.value})}/><Input label="Category" value={caseForm.category} onChange={e=>setCaseForm({...caseForm,category:e.target.value})}/><Select label="Priority" value={caseForm.priority} onChange={e=>setCaseForm({...caseForm,priority:e.target.value})}>{(ref.support_priorities||['low','normal','high','urgent']).map(x=><option key={x} value={x}>{x}</option>)}</Select><Input label="Due At" type="datetime-local" value={caseForm.due_at} onChange={e=>setCaseForm({...caseForm,due_at:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Description" value={caseForm.description} onChange={e=>setCaseForm({...caseForm,description:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveCase}><TicketCheck size={16}/>Create Support Case</Button></div></Panel></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1fr]"><Panel title="Activity / Follow-up" description="Every activity requires a customer or lead and becomes part of the CRM timeline."><div className="grid gap-3 sm:grid-cols-2"><Select label="Customer" value={activity.customer_id} onChange={e=>setActivity({...activity,customer_id:e.target.value,lead_id:''})}><option value="">Select customer</option>{customerOptions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select label="Lead" value={activity.lead_id} onChange={e=>setActivity({...activity,lead_id:e.target.value,customer_id:''})}><option value="">Select lead</option>{leadOptions.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select><Input label="Subject" value={activity.subject} onChange={e=>setActivity({...activity,subject:e.target.value})}/><Input label="Due At" type="datetime-local" value={activity.due_at} onChange={e=>setActivity({...activity,due_at:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Details" value={activity.details} onChange={e=>setActivity({...activity,details:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveActivity}><Save size={16}/>Save Follow-up</Button></div></Panel>
      <Panel title="Segmentation & Campaign" description="Create live rule-based segments and queue campaign audiences from current customer data."><div className="grid gap-3 sm:grid-cols-2"><Input label="Segment Name" value={segment.name} onChange={e=>setSegment({...segment,name:e.target.value})}/><Input label="Segment Code" value={segment.code} onChange={e=>setSegment({...segment,code:e.target.value})}/><Select label="Rule Field" value={segment.field} onChange={e=>setSegment({...segment,field:e.target.value})}><option value="loyalty_points_min">Loyalty Points Minimum</option><option value="segment">Profile Segment</option><option value="loyalty_tier">Loyalty Tier</option><option value="name_contains">Name Contains</option></Select><Input label="Rule Value" value={segment.value} onChange={e=>setSegment({...segment,value:e.target.value})}/></div><div className="mt-4"><Button busy={saving} onClick={saveSegment}><Target size={16}/>Save Segment</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Input label="Campaign Name" value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/><Select label="Channel" value={campaign.channel} onChange={e=>setCampaign({...campaign,channel:e.target.value})}>{['manual','sms','email','whatsapp','call'].map(x=><option key={x} value={x}>{x}</option>)}</Select><Select label="Segment" value={campaign.segment_id} onChange={e=>setCampaign({...campaign,segment_id:e.target.value})}><option value="">All customers</option>{segments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Input label="Schedule" type="datetime-local" value={campaign.scheduled_at} onChange={e=>setCampaign({...campaign,scheduled_at:e.target.value})}/><div className="sm:col-span-2"><Input label="Subject" value={campaign.subject} onChange={e=>setCampaign({...campaign,subject:e.target.value})}/></div><div className="sm:col-span-2"><Textarea label="Message" value={campaign.message} onChange={e=>setCampaign({...campaign,message:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveCampaign}><MailPlus size={16}/>Save Campaign</Button></div></Panel></div>
    <Panel title="Acceptance Status" description="Readiness is detected from real routes, database tables and business-rule markers." action={<Button tone="soft" onClick={()=>window.open('/api/crm/customers/export','_blank')}><Download size={16}/>Export Customers</Button>}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(acceptance.business_rules||{}).map(([key,value])=><div key={key} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--nst-dashboard-border)] px-4 py-3"><span className="text-xs font-black uppercase text-[var(--nst-dashboard-muted)]">{key.replaceAll('_',' ')}</span><span className={value?'text-emerald-500':'text-amber-500'}>{value?<CheckCircle2 size={18}/>:<FileClock size={18}/>}</span></div>)}</div></Panel>
    <Panel title="Lead Queue"><Table rows={leads} columns={[{key:'lead_no',label:'Lead'},{key:'name',label:'Name'},{key:'interest',label:'Interest'},{key:'stage',label:'Stage'},{key:'priority',label:'Priority'},{key:'estimated_value',label:'Value',render:r=>money(r.estimated_value)},{key:'next_follow_up_at',label:'Next Follow-up'},{key:'actions',label:'Action',render:r=><Button tone="soft" disabled={saving||r.stage==='won'} onClick={()=>convertLead(r.id)}><RefreshCw size={14}/>Convert</Button>}]} /></Panel>
    <Panel title="Unified Customer Profiles"><Table rows={customers} columns={[{key:'name',label:'Customer'},{key:'phone',label:'Phone'},{key:'purchase_count',label:'Purchases'},{key:'lifetime_value',label:'Lifetime Value',render:r=>money(r.lifetime_value)},{key:'due_amount',label:'Due',render:r=>money(r.due_amount)},{key:'loyalty_tier',label:'Tier'},{key:'loyalty_points',label:'Points'},{key:'open_support_count',label:'Open Support'}]} /></Panel>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Support Cases"><Table rows={support} columns={[{key:'case_no',label:'Case'},{key:'subject',label:'Subject'},{key:'customer_name',label:'Customer'},{key:'priority',label:'Priority'},{key:'status',label:'Status'},{key:'due_at',label:'SLA Due'}]} /></Panel><Panel title="Activities"><Table rows={activities} columns={[{key:'subject',label:'Subject'},{key:'activity_type',label:'Type'},{key:'customer_name',label:'Customer'},{key:'lead_name',label:'Lead'},{key:'status',label:'Status'},{key:'due_at',label:'Due'}]} /></Panel></div>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Segments"><Table rows={segments} columns={[{key:'name',label:'Segment'},{key:'code',label:'Code'},{key:'is_dynamic',label:'Dynamic',render:r=>r.is_dynamic?'Yes':'No'},{key:'is_active',label:'Active',render:r=>r.is_active?'Yes':'No'}]} /></Panel><Panel title="Campaigns"><Table rows={campaigns} columns={[{key:'campaign_no',label:'Campaign'},{key:'name',label:'Name'},{key:'channel',label:'Channel'},{key:'segment_name',label:'Segment'},{key:'audience_count',label:'Audience'},{key:'status',label:'Status'},{key:'actions',label:'Action',render:r=><Button tone="soft" disabled={saving||!['draft','scheduled'].includes(r.status)} onClick={()=>launchCampaign(r.id)}><MailPlus size={14}/>Launch</Button>}]} /></Panel></div>
    <Panel title="CRM Operation History"><Table rows={logs} columns={[{key:'action',label:'Action'},{key:'resource_type',label:'Resource'},{key:'resource_id',label:'ID'},{key:'user_name',label:'User'},{key:'branch_id',label:'Branch'},{key:'created_at',label:'Time'}]} /></Panel>
  </div>;
}
