import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import {
  BadgeDollarSign, Banknote, BookOpenCheck, Building2, CalendarCheck2, CheckCircle2,
  CircleDollarSign, ClipboardList, ContactRound, FileClock, FileText, Globe2, HandCoins,
  HeartHandshake, Landmark, LayoutDashboard, Loader2, MessageSquareText, Plus, RefreshCw,
  RotateCcw, Save, Search, ShieldCheck, Sparkles, Users, WalletCards,
} from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import FinanceStage5Center from './FinanceStage5Center';
import CrmStage6Center from './CrmStage6Center';
import HrmStage7Center from './HrmStage7Center';
import CmsStage8Center from './CmsStage8Center';
import { localDateString } from '../../utils/localDate';
import { NstPageHeader } from '../../components/ui/nst-page-header';

const MONEY = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 2 });
const money = (value) => MONEY.format(Number(value || 0));
const unwrap = (response) => response?.data?.data ?? response?.data ?? {};
const today = () => localDateString();
const monthStart = () => { const d = new Date(); return localDateString(new Date(d.getFullYear(), d.getMonth(), 1)); };

const stageMeta = {
  finance: { title: 'Accounts & Finance Center', subtitle: 'Live double-entry accounting, reconciliation and financial reporting', icon: Landmark },
  crm: { title: 'Customer Relationship Center', subtitle: 'Customer timeline, leads, follow-ups, loyalty and support intelligence', icon: HeartHandshake },
  hrm: { title: 'HRM & Payroll Center', subtitle: 'Employee lifecycle, attendance, leave, payroll and finance posting', icon: Users },
  cms: { title: 'Website CMS & Operations', subtitle: 'Draft, preview, publish, revision, SEO and public operations audit', icon: Globe2 },
};

function Metric({ label, value, note, icon: Icon = Sparkles }) {
  return <article className="rounded-3xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-5 shadow-[var(--nst-dashboard-shadow)]">
    <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[var(--nst-dashboard-muted)]">{label}</p><p className="mt-2 text-2xl font-black text-[var(--nst-dashboard-text)]">{value}</p>{note && <p className="mt-1 text-xs text-[var(--nst-dashboard-muted)]">{note}</p>}</div><span className="rounded-2xl bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_14%,transparent)] p-3 text-[var(--nst-dashboard-primary)]"><Icon size={20}/></span></div>
  </article>;
}

function Panel({ title, description, action, children }) {
  return <section className="rounded-3xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-5 shadow-[var(--nst-dashboard-shadow)]">
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-black text-[var(--nst-dashboard-text)]">{title}</h2>{description && <p className="mt-1 text-sm text-[var(--nst-dashboard-muted)]">{description}</p>}</div>{action}</div>{children}
  </section>;
}

function Table({ columns, rows = [], empty = 'No live records found.' }) {
  if (!rows.length) return <div className="rounded-2xl border border-dashed border-[var(--nst-dashboard-border)] p-8 text-center text-sm text-[var(--nst-dashboard-muted)]">{empty}</div>;
  return <div className="overflow-x-auto rounded-2xl border border-[var(--nst-dashboard-border)]"><table className="min-w-full text-left text-sm"><thead className="bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_8%,transparent)] text-xs uppercase text-[var(--nst-dashboard-muted)]"><tr>{columns.map(c => <th key={c.key} className="whitespace-nowrap px-4 py-3 font-black">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-[var(--nst-dashboard-border)]">{rows.map((row, index) => <tr key={row.id ?? index} className="hover:bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_5%,transparent)]">{columns.map(c => <td key={c.key} className="whitespace-nowrap px-4 py-3 text-[var(--nst-dashboard-text)]">{c.render ? c.render(row) : (row[c.key] ?? '-')}</td>)}</tr>)}</tbody></table></div>;
}

function Input({ label, ...props }) {
  return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<input {...props} className="mt-1.5 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]"/></label>;
}
function Select({ label, children, ...props }) {
  return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<select {...props} className="mt-1.5 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]">{children}</select></label>;
}
function Textarea({ label, ...props }) {
  return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<textarea {...props} className="mt-1.5 min-h-28 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]"/></label>;
}
function Button({ children, busy, tone = 'primary', ...props }) {
  const tones = { primary: 'bg-[var(--nst-dashboard-primary)] text-white', soft: 'bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_12%,transparent)] text-[var(--nst-dashboard-primary)]', danger: 'bg-red-500/10 text-red-500' };
  return <button type="button" {...props} disabled={busy || props.disabled} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 ${tones[tone]}`}>{busy ? <Loader2 size={16} className="animate-spin"/> : null}{children}</button>;
}

function FinanceCenter({ refreshToken }) {
  const [overview, setOverview] = useState({}); const [accounts, setAccounts] = useState([]); const [journals, setJournals] = useState([]); const [report, setReport] = useState({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ journal_date: today(), description: '', debit_account_id: '', credit_account_id: '', amount: '', post_now: true });
  const load = useCallback(async () => { setLoading(true); try { const params = { date_from: monthStart(), date_to: today() }; const [o,a,j,r] = await Promise.all([api.get('/finance/overview',{params}),api.get('/finance/accounts'),api.get('/finance/journals',{params}),api.get('/finance/reports',{params})]); setOverview(unwrap(o)); setAccounts(unwrap(a)?.accounts || []); setJournals(unwrap(j) || []); setReport(unwrap(r)); } catch(e){ toast.error(e?.response?.data?.message || 'Finance data load failed.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load, refreshToken]);
  const saveJournal = async () => { if (!form.debit_account_id || !form.credit_account_id || Number(form.amount) <= 0) return toast.error('Debit account, credit account and amount are required.'); setSaving(true); try { const created = await api.post('/finance/journals',{journal_date:form.journal_date,description:form.description,lines:[{account_id:Number(form.debit_account_id),debit:Number(form.amount),credit:0},{account_id:Number(form.credit_account_id),debit:0,credit:Number(form.amount)}]}); const journal = unwrap(created); if (!journal?.id) throw new Error('Journal ID was not returned.'); await api.post(`/finance/journals/${journal.id}/post`); toast.success('Balanced journal posted.'); setForm(f=>({...f,description:'',amount:''})); load(); } catch(e){ toast.error(e?.response?.data?.message || e?.message || 'Journal save failed.'); } finally { setSaving(false); } };
  const s = overview.summary || {}; const trial = report.trial_balance || {};
  return <div className="space-y-5">{loading && <div className="flex items-center gap-2 text-sm text-[var(--nst-dashboard-muted)]"><Loader2 className="animate-spin" size={16}/>Loading live finance data…</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Cash In" value={money(s.cash_in)} icon={HandCoins}/><Metric label="Cash Out" value={money(s.cash_out)} icon={CircleDollarSign}/><Metric label="Receivable" value={money(s.customer_receivable)} icon={WalletCards}/><Metric label="Payable" value={money(s.supplier_payable)} icon={Banknote}/></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.3fr]"><Panel title="Post Balanced Journal" description="Debit and credit must match before the API accepts the entry."><div className="grid gap-3 sm:grid-cols-2"><Input label="Journal Date" type="date" value={form.journal_date} onChange={e=>setForm({...form,journal_date:e.target.value})}/><Input label="Amount" type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Select label="Debit Account" value={form.debit_account_id} onChange={e=>setForm({...form,debit_account_id:e.target.value})}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Select label="Credit Account" value={form.credit_account_id} onChange={e=>setForm({...form,credit_account_id:e.target.value})}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><div className="sm:col-span-2"><Textarea label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveJournal}><Save size={16}/>Post Journal</Button></div></Panel>
    <Panel title="Financial Statements" description="All figures are calculated from posted ledger lines."><div className="grid gap-3 sm:grid-cols-2"><Metric label="Trial Debit" value={money(trial.total_debit)} icon={BookOpenCheck}/><Metric label="Trial Credit" value={money(trial.total_credit)} icon={BookOpenCheck}/><Metric label="Net Profit" value={money(report?.profit_and_loss?.net_profit)} icon={BadgeDollarSign}/><Metric label="Balance Difference" value={money(report?.balance_sheet?.difference)} icon={ShieldCheck}/></div></Panel></div>
    <Panel title="Chart of Accounts" description="Opening balance, branch and live ledger balance."><Table rows={accounts} columns={[{key:'code',label:'Code'},{key:'name',label:'Account'},{key:'group_name',label:'Group'},{key:'branch_name',label:'Branch'},{key:'balance',label:'Balance',render:r=>money(r.balance)}]}/></Panel>
    <Panel title="Journal History" description="Posted entries are immutable; corrections use reversal journals."><Table rows={journals} columns={[{key:'journal_no',label:'Journal'},{key:'journal_date',label:'Date'},{key:'description',label:'Description'},{key:'status',label:'Status'},{key:'branch_name',label:'Branch'}]}/></Panel>
  </div>;
}

function CrmCenter({ refreshToken }) {
  const [overview,setOverview]=useState({}); const [customers,setCustomers]=useState([]); const [leads,setLeads]=useState([]); const [activities,setActivities]=useState([]); const [saving,setSaving]=useState(false); const [form,setForm]=useState({name:'',phone:'',email:'',interest:'',estimated_value:'',priority:'normal'});
  const load=useCallback(async()=>{try{const[o,c,l,a]=await Promise.all([api.get('/crm/overview'),api.get('/crm/customers'),api.get('/crm/leads'),api.get('/crm/activities')]);setOverview(unwrap(o));setCustomers(unwrap(c)||[]);setLeads(unwrap(l)||[]);setActivities(unwrap(a)||[]);}catch(e){toast.error(e?.response?.data?.message||'CRM data load failed.');}},[]); useEffect(()=>{load();},[load,refreshToken]);
  const save=async()=>{if(!form.name)return toast.error('Lead name is required.');setSaving(true);try{await api.post('/crm/leads',{...form,estimated_value:Number(form.estimated_value||0)});toast.success('Lead created.');setForm({name:'',phone:'',email:'',interest:'',estimated_value:'',priority:'normal'});load();}catch(e){toast.error(e?.response?.data?.message||'Lead save failed.');}finally{setSaving(false);}}; const s=overview.summary||{};
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Customers" value={Number(s.customers||0).toLocaleString()} icon={ContactRound}/><Metric label="Active Leads" value={s.active_leads||0} icon={HeartHandshake}/><Metric label="Won Value" value={money(s.won_value)} icon={BadgeDollarSign}/><Metric label="Open Tickets" value={s.open_support_tickets||0} icon={MessageSquareText}/></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><Panel title="Create Lead" description="Assign and progress the opportunity from new to won/lost."><div className="grid gap-3 sm:grid-cols-2"><Input label="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Input label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input label="Estimated Value" type="number" min="0" value={form.estimated_value} onChange={e=>setForm({...form,estimated_value:e.target.value})}/><Select label="Priority" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></Select><div className="sm:col-span-2"><Textarea label="Product / Service Interest" value={form.interest} onChange={e=>setForm({...form,interest:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={save}><Plus size={16}/>Create Lead</Button></div></Panel>
    <Panel title="Pipeline" description="Live lead stages and estimated values."><Table rows={overview.lead_pipeline||[]} columns={[{key:'stage',label:'Stage'},{key:'total',label:'Leads'},{key:'value',label:'Value',render:r=>money(r.value)}]}/></Panel></div>
    <Panel title="Unified Customer Profiles" description="Purchase count, lifetime value, due and loyalty are linked to existing customer records."><Table rows={customers} columns={[{key:'name',label:'Customer'},{key:'phone',label:'Phone'},{key:'purchase_count',label:'Purchases'},{key:'lifetime_value',label:'Lifetime Value',render:r=>money(r.lifetime_value)},{key:'due_amount',label:'Due',render:r=>money(r.due_amount)},{key:'loyalty_tier',label:'Tier'},{key:'loyalty_points',label:'Points'}]}/></Panel>
    <Panel title="Lead & Follow-up Queue"><Table rows={leads} columns={[{key:'lead_no',label:'Lead'},{key:'name',label:'Name'},{key:'interest',label:'Interest'},{key:'stage',label:'Stage'},{key:'priority',label:'Priority'},{key:'estimated_value',label:'Value',render:r=>money(r.estimated_value)},{key:'next_follow_up_at',label:'Next Follow-up'}]}/></Panel>
    <Panel title="CRM Activities"><Table rows={activities} columns={[{key:'subject',label:'Subject'},{key:'activity_type',label:'Type'},{key:'customer_name',label:'Customer'},{key:'lead_name',label:'Lead'},{key:'status',label:'Status'},{key:'due_at',label:'Due'}]}/></Panel>
  </div>;
}

function HrmCenter({ refreshToken, moduleKey }) {
  const [overview,setOverview]=useState({}); const [ref,setRef]=useState({}); const [employees,setEmployees]=useState([]); const [attendance,setAttendance]=useState([]); const [leaves,setLeaves]=useState([]); const [payroll,setPayroll]=useState([]); const [saving,setSaving]=useState(false);
  const [employee,setEmployee]=useState({name:'',phone:'',email:'',branch_id:'',department_id:'',designation_id:'',shift_id:'',employment_type:'full_time',joining_date:today()});
  const [payForm,setPayForm]=useState({name:`Payroll ${new Date().toLocaleString('en',{month:'long',year:'numeric'})}`,starts_on:monthStart(),ends_on:today(),branch_id:''});
  const load=useCallback(async()=>{try{const[o,r,e,a,l,p]=await Promise.all([api.get('/hrm/overview'),api.get('/hrm/reference-data'),api.get('/hrm/employees'),api.get('/hrm/attendance',{params:{date_from:monthStart(),date_to:today()}}),api.get('/hrm/leaves'),api.get('/hrm/payroll')]);setOverview(unwrap(o));setRef(unwrap(r));setEmployees(unwrap(e)||[]);setAttendance(unwrap(a)||[]);setLeaves(unwrap(l)||[]);setPayroll(unwrap(p)||[]);}catch(e){toast.error(e?.response?.data?.message||'HRM data load failed.');}},[]); useEffect(()=>{load();},[load,refreshToken]);
  const saveEmployee=async()=>{if(!employee.name)return toast.error('Employee name is required.');setSaving(true);try{const payload={...employee};['branch_id','department_id','designation_id','shift_id'].forEach(k=>{payload[k]=payload[k]?Number(payload[k]):null;});await api.post('/hrm/employees',payload);toast.success('Employee created.');setEmployee({...employee,name:'',phone:'',email:''});load();}catch(e){toast.error(e?.response?.data?.message||'Employee save failed.');}finally{setSaving(false);}};
  const generatePayroll=async()=>{setSaving(true);try{await api.post('/hrm/payroll/generate',{...payForm,branch_id:payForm.branch_id?Number(payForm.branch_id):null});toast.success('Payroll generated.');load();}catch(e){toast.error(e?.response?.data?.message||'Payroll generation failed.');}finally{setSaving(false);}}; const s=overview.summary||{};
  return <div className="space-y-5">{moduleKey && <div className="rounded-2xl bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_10%,transparent)] px-4 py-3 text-sm font-bold text-[var(--nst-dashboard-primary)]">Active HR workspace: {String(moduleKey).replaceAll('-',' ')}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active Employees" value={s.active_employees||0} icon={Users}/><Metric label="Present Today" value={s.present_today||0} icon={CalendarCheck2}/><Metric label="Pending Leave" value={s.pending_leave||0} icon={FileClock}/><Metric label="Payroll Due" value={money(s.payroll_due)} icon={Banknote}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Add Employee" description="Link branch, department, designation and shift without creating fake user data."><div className="grid gap-3 sm:grid-cols-2"><Input label="Name" value={employee.name} onChange={e=>setEmployee({...employee,name:e.target.value})}/><Input label="Phone" value={employee.phone} onChange={e=>setEmployee({...employee,phone:e.target.value})}/><Input label="Email" type="email" value={employee.email} onChange={e=>setEmployee({...employee,email:e.target.value})}/><Input label="Joining Date" type="date" value={employee.joining_date} onChange={e=>setEmployee({...employee,joining_date:e.target.value})}/><Select label="Branch" value={employee.branch_id} onChange={e=>setEmployee({...employee,branch_id:e.target.value})}><option value="">All / unassigned</option>{(ref.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Department" value={employee.department_id} onChange={e=>setEmployee({...employee,department_id:e.target.value})}><option value="">Select</option>{(ref.departments||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Designation" value={employee.designation_id} onChange={e=>setEmployee({...employee,designation_id:e.target.value})}><option value="">Select</option>{(ref.designations||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Shift" value={employee.shift_id} onChange={e=>setEmployee({...employee,shift_id:e.target.value})}><option value="">Select</option>{(ref.shifts||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></div><div className="mt-4"><Button busy={saving} onClick={saveEmployee}><Plus size={16}/>Add Employee</Button></div></Panel>
    <Panel title="Generate Payroll" description="Uses active salary structures; payment later posts a balanced finance journal."><div className="grid gap-3 sm:grid-cols-2"><Input label="Period Name" value={payForm.name} onChange={e=>setPayForm({...payForm,name:e.target.value})}/><Select label="Branch" value={payForm.branch_id} onChange={e=>setPayForm({...payForm,branch_id:e.target.value})}><option value="">All branches</option>{(ref.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Input label="From" type="date" value={payForm.starts_on} onChange={e=>setPayForm({...payForm,starts_on:e.target.value})}/><Input label="To" type="date" value={payForm.ends_on} onChange={e=>setPayForm({...payForm,ends_on:e.target.value})}/></div><div className="mt-4"><Button busy={saving} onClick={generatePayroll}><Banknote size={16}/>Generate Payroll</Button></div></Panel></div>
    <Panel title="Employees"><Table rows={employees} columns={[{key:'employee_no',label:'Employee No'},{key:'name',label:'Name'},{key:'branch_name',label:'Branch'},{key:'department_name',label:'Department'},{key:'designation_name',label:'Designation'},{key:'shift_name',label:'Shift'},{key:'status',label:'Status'}]}/></Panel>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Attendance"><Table rows={attendance.slice(0,100)} columns={[{key:'attendance_date',label:'Date'},{key:'employee_name',label:'Employee'},{key:'check_in',label:'In'},{key:'check_out',label:'Out'},{key:'late_minutes',label:'Late'},{key:'status',label:'Status'}]}/></Panel><Panel title="Leave Requests"><Table rows={leaves} columns={[{key:'employee_name',label:'Employee'},{key:'leave_type_name',label:'Type'},{key:'starts_on',label:'From'},{key:'ends_on',label:'To'},{key:'days',label:'Days'},{key:'status',label:'Status'}]}/></Panel></div>
    <Panel title="Payroll Periods"><Table rows={payroll} columns={[{key:'period_no',label:'Period'},{key:'name',label:'Name'},{key:'branch_name',label:'Branch'},{key:'gross_total',label:'Gross',render:r=>money(r.gross_total)},{key:'deduction_total',label:'Deduction',render:r=>money(r.deduction_total)},{key:'net_total',label:'Net',render:r=>money(r.net_total)},{key:'status',label:'Status'}]}/></Panel>
  </div>;
}

function CmsCenter({ refreshToken }) {
  const [overview,setOverview]=useState({}); const [pages,setPages]=useState([]); const [logs,setLogs]=useState([]); const [saving,setSaving]=useState(false); const [form,setForm]=useState({title:'',route:'',page_type:'custom',content:'',meta_title:'',meta_description:'',is_visible:true});
  const load=useCallback(async()=>{try{const[o,p,l]=await Promise.all([api.get('/cms-operations/overview'),api.get('/cms-operations/pages'),api.get('/cms-operations/publication-logs')]);setOverview(unwrap(o));setPages(unwrap(p)||[]);setLogs(unwrap(l)||[]);}catch(e){toast.error(e?.response?.data?.message||'CMS operations load failed.');}},[]); useEffect(()=>{load();},[load,refreshToken]);
  const save=async()=>{if(!form.title)return toast.error('Page title is required.');setSaving(true);try{await api.post('/cms-operations/pages',{title:form.title,route:form.route||undefined,page_type:form.page_type,content:{type:'rich_text',html:form.content},seo:{meta_title:form.meta_title||form.title,meta_description:form.meta_description,robots:'index,follow'},faq:[],settings:{responsive:true},is_visible:form.is_visible});toast.success('CMS page draft created.');setForm({...form,title:'',route:'',content:'',meta_title:'',meta_description:''});load();}catch(e){toast.error(e?.response?.data?.message||'CMS page save failed.');}finally{setSaving(false);}};
  const publish=async(id)=>{try{await api.post(`/cms-operations/pages/${id}/publish`);toast.success('Page published.');load();}catch(e){toast.error(e?.response?.data?.message||'Publish failed.');}}; const s=overview.summary||{}; const health=overview.content_health||{};
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="CMS Pages" value={s.cms_pages||0} icon={FileText}/><Metric label="Published" value={s.published_pages||0} icon={CheckCircle2}/><Metric label="Revisions" value={s.page_revisions||0} icon={FileClock}/><Metric label="Missing SEO" value={health.missing_seo_count||0} icon={Search}/></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Create CMS Page Draft" description="Publishing is a separate Super Admin action with rollback history."><div className="grid gap-3 sm:grid-cols-2"><Input label="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><Input label="Route" placeholder="/about-us" value={form.route} onChange={e=>setForm({...form,route:e.target.value})}/><Input label="Meta Title" value={form.meta_title} onChange={e=>setForm({...form,meta_title:e.target.value})}/><Input label="Meta Description" value={form.meta_description} onChange={e=>setForm({...form,meta_description:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Page Content" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={save}><Save size={16}/>Save Draft</Button></div></Panel>
    <Panel title="Connected Operations Audit" description="This status is detected from real routes, files and database tables."><div className="space-y-3">{Object.entries(overview.integration||{}).map(([key,value])=><div key={key} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--nst-dashboard-border)] px-4 py-3"><span className="text-sm font-bold text-[var(--nst-dashboard-text)]">{key.replaceAll('_',' ')}</span><span className={value?'text-emerald-500':'text-amber-500'}>{value?<CheckCircle2 size={18}/>:<FileClock size={18}/>}</span></div>)}</div></Panel></div>
    <Panel title="CMS Pages" description="Draft pages are not public until explicitly published."><Table rows={pages} columns={[{key:'title',label:'Title'},{key:'route',label:'Route'},{key:'page_type',label:'Type'},{key:'status',label:'Status'},{key:'published_at',label:'Published At'},{key:'actions',label:'Action',render:r=><Button tone="soft" disabled={r.status==='published'||!r.is_visible} onClick={()=>publish(r.id)}><Globe2 size={14}/>Publish</Button>}]}/></Panel>
    <Panel title="Publication & Rollback Audit"><Table rows={logs} columns={[{key:'action',label:'Action'},{key:'resource_type',label:'Resource'},{key:'resource_id',label:'ID'},{key:'user_name',label:'User'},{key:'environment',label:'Environment'},{key:'created_at',label:'Time'}]}/></Panel>
  </div>;
}

export function EnterpriseModuleRouter() {
  const { moduleKey } = useParams();
  if (String(moduleKey || '').startsWith('hr-') || ['payroll','salary-structure','payslip'].includes(moduleKey)) return <EnterpriseSuitePage stage="hrm" moduleKey={moduleKey}/>;
  return <EnterpriseSuitePage stage="hrm" moduleKey={moduleKey}/>;
}

export default function EnterpriseSuitePage({ stage = 'finance', moduleKey = '' }) {
  const [refreshToken,setRefreshToken]=useState(0); const meta=stageMeta[stage]||stageMeta.finance; const Icon=meta.icon;
  const body=useMemo(()=>({finance:<FinanceStage5Center refreshToken={refreshToken}/>,crm:<CrmStage6Center refreshToken={refreshToken}/>,hrm:<HrmStage7Center refreshToken={refreshToken} moduleKey={moduleKey}/>,cms:<CmsStage8Center refreshToken={refreshToken}/>}[stage]),[stage,refreshToken,moduleKey]);
  return <main className="min-h-full bg-[var(--nst-dashboard-bg)] p-4 text-[var(--nst-dashboard-text)] md:p-7"><div className="mx-auto max-w-[1600px] space-y-6"><NstPageHeader icon={Icon} title={<>{meta.title}</>} subtitle={<>{meta.subtitle}</>} actions={<><Button tone="soft" onClick={()=>setRefreshToken(v=>v+1)}><RefreshCw size={16}/>Refresh Live Data</Button></>}/>{body}</div></main>;
}
