import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  ArrowLeftRight, Banknote, BookOpenCheck, CheckCircle2, ClipboardList, Download,
  FileClock, HandCoins, Landmark, Loader2, Plus, RefreshCw, RotateCcw, Save,
  ShieldCheck, WalletCards,
} from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import { localDateString } from '../../utils/localDate';

const MONEY = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 2 });
const money = (value) => MONEY.format(Number(value || 0));
const unwrap = (response) => response?.data?.data ?? response?.data ?? {};
const today = () => localDateString();
const monthStart = () => { const d = new Date(); return localDateString(new Date(d.getFullYear(), d.getMonth(), 1)); };

function Metric({ label, value, note, icon: Icon = Landmark }) {
  return <article className="rounded-3xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-5 shadow-[var(--nst-dashboard-shadow)]">
    <div className="flex items-start justify-between gap-3">
      <div><p className="text-xs font-black uppercase tracking-wider text-[var(--nst-dashboard-muted)]">{label}</p><p className="mt-2 text-2xl font-black text-[var(--nst-dashboard-text)]">{value}</p>{note && <p className="mt-1 text-xs text-[var(--nst-dashboard-muted)]">{note}</p>}</div>
      <span className="rounded-2xl bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_14%,transparent)] p-3 text-[var(--nst-dashboard-primary)]"><Icon size={20}/></span>
    </div>
  </article>;
}

function Panel({ title, description, action, children }) {
  return <section className="rounded-3xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-surface)] p-5 shadow-[var(--nst-dashboard-shadow)]">
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
      <div><h2 className="text-lg font-black text-[var(--nst-dashboard-text)]">{title}</h2>{description && <p className="mt-1 text-sm text-[var(--nst-dashboard-muted)]">{description}</p>}</div>{action}
    </div>
    {children}
  </section>;
}

function Button({ children, busy, tone = 'primary', ...props }) {
  const tones = { primary: 'bg-[var(--nst-dashboard-primary)] text-white', soft: 'bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_12%,transparent)] text-[var(--nst-dashboard-primary)]', danger: 'bg-red-500/10 text-red-500' };
  return <button type="button" {...props} disabled={busy || props.disabled} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 ${tones[tone]}`}>
    {busy ? <Loader2 size={16} className="animate-spin"/> : null}{children}
  </button>;
}

function Input({ label, ...props }) {
  return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<input {...props} className="mt-1.5 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]"/></label>;
}
function Select({ label, children, ...props }) {
  return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<select {...props} className="mt-1.5 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]">{children}</select></label>;
}
function Textarea({ label, ...props }) {
  return <label className="text-xs font-black uppercase tracking-wide text-[var(--nst-dashboard-muted)]">{label}<textarea {...props} className="mt-1.5 min-h-24 w-full rounded-xl border border-[var(--nst-dashboard-border)] bg-[var(--nst-dashboard-bg)] px-3 py-2.5 text-sm text-[var(--nst-dashboard-text)] outline-none focus:border-[var(--nst-dashboard-primary)]"/></label>;
}
function Table({ columns, rows = [], empty = 'No live records found.' }) {
  if (!rows.length) return <div className="rounded-2xl border border-dashed border-[var(--nst-dashboard-border)] p-8 text-center text-sm text-[var(--nst-dashboard-muted)]">{empty}</div>;
  return <div className="overflow-x-auto rounded-2xl border border-[var(--nst-dashboard-border)]"><table className="min-w-full text-left text-sm"><thead className="bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_8%,transparent)] text-xs uppercase text-[var(--nst-dashboard-muted)]"><tr>{columns.map(c => <th key={c.key} className="whitespace-nowrap px-4 py-3 font-black">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-[var(--nst-dashboard-border)]">{rows.map((row, index) => <tr key={row.id ?? index} className="hover:bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_5%,transparent)]">{columns.map(c => <td key={c.key} className="whitespace-nowrap px-4 py-3 text-[var(--nst-dashboard-text)]">{c.render ? c.render(row) : (row[c.key] ?? '-')}</td>)}</tr>)}</tbody></table></div>;
}

export default function FinanceStage5Center({ refreshToken }) {
  const [active, setActive] = useState('journal');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [overview, setOverview] = useState({});
  const [refs, setRefs] = useState({ accounts: [], cash_bank_accounts: [], expense_accounts: [], asset_accounts: [], liability_accounts: [], expense_categories: [], branches: [], groups: [] });
  const [journals, setJournals] = useState([]);
  const [expenses, setExpenses] = useState([]);
  const [transfers, setTransfers] = useState([]);
  const [duePayments, setDuePayments] = useState([]);
  const [cashSessions, setCashSessions] = useState([]);
  const [reconciliations, setReconciliations] = useState([]);
  const [report, setReport] = useState({});
  const [audit, setAudit] = useState([]);
  const [acceptance, setAcceptance] = useState({});

  const [filters, setFilters] = useState({ date_from: monthStart(), date_to: today(), branch_id: '' });
  const [journal, setJournal] = useState({ journal_date: today(), description: '', reference_no: '', branch_id: '', debit_account_id: '', credit_account_id: '', amount: '' });
  const [expense, setExpense] = useState({ expense_date: today(), category_id: '', expense_account_id: '', payment_account_id: '', branch_id: '', vendor_name: '', amount: '', tax_amount: '0', payment_method: 'cash', status: 'paid', note: '' });
  const [transfer, setTransfer] = useState({ transfer_date: today(), from_account_id: '', to_account_id: '', branch_id: '', amount: '', fee_amount: '0', note: '' });
  const [due, setDue] = useState({ payment_date: today(), payment_direction: 'customer_collection', party_type: 'customer', party_id: '', account_id: '', cash_bank_account_id: '', branch_id: '', amount: '', method: 'cash', reference_no: '', note: '' });
  const [cash, setCash] = useState({ branch_id: '', cash_account_id: '', opening_amount: '', counted_closing_amount: '', note: '' });
  const [recon, setRecon] = useState({ provider: 'manual', channel: 'cash', external_reference: '', internal_reference: '', expected_amount: '', received_amount: '', branch_id: '', status: 'pending', note: '' });
  const [account, setAccount] = useState({ group_id: '', name: '', code: '', account_kind: 'ledger', opening_balance: '0', opening_side: 'debit', branch_id: '', is_cash: false, is_bank: false });

  const params = useMemo(() => ({ date_from: filters.date_from, date_to: filters.date_to, ...(filters.branch_id ? { branch_id: filters.branch_id } : {}) }), [filters]);
  const accounts = refs.accounts || [];
  const cashAccounts = refs.cash_bank_accounts?.length ? refs.cash_bank_accounts : accounts.filter(a => a.is_cash || a.is_bank);
  const expenseAccounts = refs.expense_accounts?.length ? refs.expense_accounts : accounts.filter(a => a.group_type === 'expense');
  const assetAccounts = refs.asset_accounts?.length ? refs.asset_accounts : accounts.filter(a => a.group_type === 'asset');
  const liabilityAccounts = refs.liability_accounts?.length ? refs.liability_accounts : accounts.filter(a => a.group_type === 'liability');

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [o, r, j, e, t, d, c, rec, rep, a, ok] = await Promise.all([
        api.get('/finance/overview', { params }), api.get('/finance/reference-data'), api.get('/finance/journals', { params }), api.get('/finance/expenses', { params }), api.get('/finance/transfers', { params }), api.get('/finance/due-payments', { params }), api.get('/finance/cash-sessions'), api.get('/finance/reconciliations', { params }), api.get('/finance/reports', { params }), api.get('/finance/audit-history'), api.get('/finance/acceptance-status'),
      ]);
      setOverview(unwrap(o)); setRefs(unwrap(r)); setJournals(unwrap(j) || []); setExpenses(unwrap(e) || []); setTransfers(unwrap(t) || []); setDuePayments(unwrap(d) || []); setCashSessions(unwrap(c) || []); setReconciliations(unwrap(rec) || []); setReport(unwrap(rep)); setAudit(unwrap(a)?.logs || []); setAcceptance(unwrap(ok));
    } catch (err) {
      toast.error(err?.response?.data?.message || 'Finance live data load failed.');
    } finally { setLoading(false); }
  }, [params]);

  useEffect(() => { load(); }, [load, refreshToken]);

  const postJournal = async () => {
    if (!journal.debit_account_id || !journal.credit_account_id || Number(journal.amount) <= 0) return toast.error('Debit, credit and amount are required.');
    setSaving(true);
    try {
      const created = await api.post('/finance/journals', { journal_date: journal.journal_date, reference_no: journal.reference_no || undefined, branch_id: journal.branch_id || undefined, description: journal.description, lines: [{ account_id: Number(journal.debit_account_id), debit: Number(journal.amount), credit: 0 }, { account_id: Number(journal.credit_account_id), debit: 0, credit: Number(journal.amount) }] });
      const row = unwrap(created); await api.post(`/finance/journals/${row.id}/post`);
      toast.success('Balanced journal saved to server and posted.'); setJournal({ ...journal, description: '', reference_no: '', amount: '' }); load();
    } catch (err) { toast.error(err?.response?.data?.message || 'Journal posting failed.'); } finally { setSaving(false); }
  };
  const saveAccount = async () => {
    if (!account.group_id || !account.name || !account.code) return toast.error('Group, account name and code are required.');
    setSaving(true); try { await api.post('/finance/accounts', { ...account, branch_id: account.branch_id || undefined, is_cash: Boolean(account.is_cash), is_bank: Boolean(account.is_bank), opening_balance: Number(account.opening_balance || 0) }); toast.success('Account saved with database persistence.'); setAccount({ group_id: '', name: '', code: '', account_kind: 'ledger', opening_balance: '0', opening_side: 'debit', branch_id: '', is_cash: false, is_bank: false }); load(); } catch (err) { toast.error(err?.response?.data?.message || 'Account save failed.'); } finally { setSaving(false); }
  };
  const saveExpense = async () => {
    if (!expense.expense_account_id || !expense.payment_account_id || Number(expense.amount) <= 0) return toast.error('Expense account, payment account and amount are required.');
    setSaving(true); try { await api.post('/finance/expenses', { ...expense, category_id: expense.category_id || undefined, branch_id: expense.branch_id || undefined, amount: Number(expense.amount), tax_amount: Number(expense.tax_amount || 0) }); toast.success('Expense saved and paid ledger entry posted.'); setExpense({ ...expense, vendor_name: '', amount: '', tax_amount: '0', note: '' }); load(); } catch (err) { toast.error(err?.response?.data?.message || 'Expense save failed.'); } finally { setSaving(false); }
  };
  const saveTransfer = async () => {
    if (!transfer.from_account_id || !transfer.to_account_id || Number(transfer.amount) <= 0) return toast.error('From, To and amount are required.');
    setSaving(true); try { await api.post('/finance/transfers', { ...transfer, branch_id: transfer.branch_id || undefined, amount: Number(transfer.amount), fee_amount: Number(transfer.fee_amount || 0) }); toast.success('Fund transfer posted to ledger.'); setTransfer({ ...transfer, amount: '', fee_amount: '0', note: '' }); load(); } catch (err) { toast.error(err?.response?.data?.message || 'Transfer failed.'); } finally { setSaving(false); }
  };
  const saveDue = async () => {
    if (!due.account_id || !due.cash_bank_account_id || Number(due.amount) <= 0) return toast.error('Ledger account, cash/bank account and amount are required.');
    setSaving(true); try { await api.post('/finance/due-payments', { ...due, party_id: due.party_id || undefined, branch_id: due.branch_id || undefined, amount: Number(due.amount) }); toast.success('Due payment/collection posted.'); setDue({ ...due, party_id: '', amount: '', reference_no: '', note: '' }); load(); } catch (err) { toast.error(err?.response?.data?.message || 'Due transaction failed.'); } finally { setSaving(false); }
  };
  const openCash = async () => { if (Number(cash.opening_amount) < 0 || cash.opening_amount === '') return toast.error('Opening amount is required.'); setSaving(true); try { await api.post('/finance/cash-sessions/open', { branch_id: cash.branch_id || undefined, cash_account_id: cash.cash_account_id || undefined, opening_amount: Number(cash.opening_amount), note: cash.note }); toast.success('Cash session opened.'); setCash({ ...cash, opening_amount: '', note: '' }); load(); } catch (err) { toast.error(err?.response?.data?.message || 'Cash session open failed.'); } finally { setSaving(false); } };
  const closeCash = async (id) => { if (cash.counted_closing_amount === '') return toast.error('Counted closing amount required.'); setSaving(true); try { await api.post(`/finance/cash-sessions/${id}/close`, { counted_closing_amount: Number(cash.counted_closing_amount), note: cash.note }); toast.success('Cash session submitted.'); setCash({ ...cash, counted_closing_amount: '', note: '' }); load(); } catch (err) { toast.error(err?.response?.data?.message || 'Cash closing failed.'); } finally { setSaving(false); } };
  const saveRecon = async () => { if (!recon.provider || Number(recon.received_amount) < 0 || Number(recon.expected_amount) < 0) return toast.error('Provider and amounts are required.'); setSaving(true); try { await api.post('/finance/reconciliations', { ...recon, branch_id: recon.branch_id || undefined, expected_amount: Number(recon.expected_amount || 0), received_amount: Number(recon.received_amount || 0) }); toast.success('Reconciliation saved.'); setRecon({ ...recon, external_reference: '', internal_reference: '', expected_amount: '', received_amount: '', note: '' }); load(); } catch (err) { toast.error(err?.response?.data?.message || 'Reconciliation failed.'); } finally { setSaving(false); } };
  const downloadReport = () => { window.open(`${api.defaults.baseURL}/finance/reports/export?date_from=${filters.date_from}&date_to=${filters.date_to}${filters.branch_id ? `&branch_id=${filters.branch_id}` : ''}`, '_blank', 'noopener,noreferrer'); };

  const s = overview.summary || {}; const trial = report.trial_balance || {}; const pnl = report.profit_and_loss || {}; const sheet = report.balance_sheet || {};
  const tabs = [ ['journal', 'Journal'], ['account', 'Accounts'], ['expense', 'Expenses'], ['transfer', 'Transfers'], ['due', 'Due'], ['cash', 'Cash Closing'], ['recon', 'Reconciliation'], ['reports', 'Reports'], ['audit', 'Audit'] ];

  return <div className="space-y-5">
    <Panel title="Accounts & Finance Acceptance" description="This center uses real API/database state. Browser-only save fallback is not treated as success." action={<Button tone="soft" onClick={load}><RefreshCw size={16}/>Reload Server State</Button>}>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Cash In" value={money(s.cash_in)} icon={HandCoins}/><Metric label="Cash Out" value={money(s.cash_out)} icon={Banknote}/><Metric label="Receivable" value={money(s.customer_receivable)} icon={WalletCards}/><Metric label="Payable" value={money(s.supplier_payable)} icon={BookOpenCheck}/><Metric label="DB Ready" value={acceptance.database_ready ? 'YES' : 'NO'} note={acceptance.routes_ready ? 'Routes ready' : 'Route check pending'} icon={acceptance.database_ready ? CheckCircle2 : FileClock}/></div>{overview.accounting_reconciliation && <div className="mt-4 grid gap-4 sm:grid-cols-3"><Metric label="Operational Net Cash" value={money(overview.accounting_reconciliation.operational?.net_cash)} icon={HandCoins}/><Metric label="Ledger Net Cash" value={money(overview.accounting_reconciliation.ledger?.net_cash)} icon={Landmark}/><Metric label="Reconciliation Difference" value={money(overview.accounting_reconciliation.difference)} note={overview.accounting_reconciliation.status === 'match' ? 'MATCH' : 'ATTENTION: operational and ledger cash differ'} icon={ShieldCheck}/></div>}
      <div className="mt-5 grid gap-3 md:grid-cols-4"><Input label="From" type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/><Input label="To" type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/><Select label="Branch" value={filters.branch_id} onChange={e=>setFilters({...filters,branch_id:e.target.value})}><option value="">All branches</option>{(refs.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><div className="flex items-end"><Button tone="soft" onClick={load} busy={loading}><RefreshCw size={16}/>Apply Filter</Button></div></div>
    </Panel>

    <div className="flex flex-wrap gap-2">{tabs.map(([key, label]) => <button type="button" key={key} onClick={()=>setActive(key)} className={`rounded-full px-4 py-2 text-sm font-black ${active===key?'bg-[var(--nst-dashboard-primary)] text-white':'bg-[color-mix(in_srgb,var(--nst-dashboard-primary)_10%,transparent)] text-[var(--nst-dashboard-primary)]'}`}>{label}</button>)}</div>

    {active === 'journal' && <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Post Balanced Journal" description="API creates draft first, then posts only after balance validation and permission check."><div className="grid gap-3 sm:grid-cols-2"><Input label="Date" type="date" value={journal.journal_date} onChange={e=>setJournal({...journal,journal_date:e.target.value})}/><Input label="Amount" type="number" step="0.01" min="0" value={journal.amount} onChange={e=>setJournal({...journal,amount:e.target.value})}/><Select label="Debit Account" value={journal.debit_account_id} onChange={e=>setJournal({...journal,debit_account_id:e.target.value})}><option value="">Select</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Select label="Credit Account" value={journal.credit_account_id} onChange={e=>setJournal({...journal,credit_account_id:e.target.value})}><option value="">Select</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Input label="Reference" value={journal.reference_no} onChange={e=>setJournal({...journal,reference_no:e.target.value})}/><Select label="Branch" value={journal.branch_id} onChange={e=>setJournal({...journal,branch_id:e.target.value})}><option value="">All / none</option>{(refs.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><div className="sm:col-span-2"><Textarea label="Description" value={journal.description} onChange={e=>setJournal({...journal,description:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={postJournal}><Save size={16}/>Save & Post</Button></div></Panel><Panel title="Recent Journals"><Table rows={journals} columns={[{key:'journal_no',label:'Journal No'},{key:'journal_date',label:'Date'},{key:'status',label:'Status'},{key:'description',label:'Description'}]}/></Panel></div>}

    {active === 'account' && <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Create Ledger Account" description="Opening balance is persisted in database and reflected in live account balance."><div className="grid gap-3 sm:grid-cols-2"><Select label="Group" value={account.group_id} onChange={e=>setAccount({...account,group_id:e.target.value})}><option value="">Select</option>{(refs.groups||[]).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</Select><Input label="Code" value={account.code} onChange={e=>setAccount({...account,code:e.target.value})}/><Input label="Name" value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/><Input label="Kind" value={account.account_kind} onChange={e=>setAccount({...account,account_kind:e.target.value})}/><Input label="Opening Balance" type="number" value={account.opening_balance} onChange={e=>setAccount({...account,opening_balance:e.target.value})}/><Select label="Opening Side" value={account.opening_side} onChange={e=>setAccount({...account,opening_side:e.target.value})}><option value="debit">Debit</option><option value="credit">Credit</option></Select><label className="flex items-center gap-2 text-sm font-bold text-[var(--nst-dashboard-muted)]"><input type="checkbox" checked={account.is_cash} onChange={e=>setAccount({...account,is_cash:e.target.checked})}/> Cash account</label><label className="flex items-center gap-2 text-sm font-bold text-[var(--nst-dashboard-muted)]"><input type="checkbox" checked={account.is_bank} onChange={e=>setAccount({...account,is_bank:e.target.checked})}/> Bank account</label></div><div className="mt-4"><Button busy={saving} onClick={saveAccount}><Plus size={16}/>Create Account</Button></div></Panel><Panel title="Chart of Accounts"><Table rows={accounts} columns={[{key:'code',label:'Code'},{key:'name',label:'Name'},{key:'group_type',label:'Type'},{key:'balance',label:'Balance',render:r=>money(r.balance)}]}/></Panel></div>}

    {active === 'expense' && <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Record Paid Expense" description="Paid expense creates a balanced journal: debit expense, credit cash/bank."><div className="grid gap-3 sm:grid-cols-2"><Input label="Date" type="date" value={expense.expense_date} onChange={e=>setExpense({...expense,expense_date:e.target.value})}/><Select label="Category" value={expense.category_id} onChange={e=>setExpense({...expense,category_id:e.target.value})}><option value="">Select</option>{(refs.expense_categories||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Expense Account" value={expense.expense_account_id} onChange={e=>setExpense({...expense,expense_account_id:e.target.value})}><option value="">Select</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Select label="Payment Account" value={expense.payment_account_id} onChange={e=>setExpense({...expense,payment_account_id:e.target.value})}><option value="">Select</option>{cashAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Input label="Vendor" value={expense.vendor_name} onChange={e=>setExpense({...expense,vendor_name:e.target.value})}/><Input label="Amount" type="number" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/><Input label="Tax" type="number" value={expense.tax_amount} onChange={e=>setExpense({...expense,tax_amount:e.target.value})}/><Select label="Branch" value={expense.branch_id} onChange={e=>setExpense({...expense,branch_id:e.target.value})}><option value="">All / none</option>{(refs.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><div className="sm:col-span-2"><Textarea label="Note" value={expense.note} onChange={e=>setExpense({...expense,note:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveExpense}><Save size={16}/>Save Expense</Button></div></Panel><Panel title="Expense Register"><Table rows={expenses} columns={[{key:'expense_no',label:'No'},{key:'expense_date',label:'Date'},{key:'category_name',label:'Category'},{key:'total_amount',label:'Total',render:r=>money(r.total_amount)},{key:'status',label:'Status'}]}/></Panel></div>}

    {active === 'transfer' && <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Cash/Bank Fund Transfer" description="Creates a posted contra-style journal from source account to target account."><div className="grid gap-3 sm:grid-cols-2"><Input label="Date" type="date" value={transfer.transfer_date} onChange={e=>setTransfer({...transfer,transfer_date:e.target.value})}/><Input label="Amount" type="number" value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:e.target.value})}/><Select label="From Account" value={transfer.from_account_id} onChange={e=>setTransfer({...transfer,from_account_id:e.target.value})}><option value="">Select</option>{cashAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Select label="To Account" value={transfer.to_account_id} onChange={e=>setTransfer({...transfer,to_account_id:e.target.value})}><option value="">Select</option>{cashAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Select label="Branch" value={transfer.branch_id} onChange={e=>setTransfer({...transfer,branch_id:e.target.value})}><option value="">All / none</option>{(refs.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Input label="Fee" type="number" value={transfer.fee_amount} onChange={e=>setTransfer({...transfer,fee_amount:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Note" value={transfer.note} onChange={e=>setTransfer({...transfer,note:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveTransfer}><ArrowLeftRight size={16}/>Post Transfer</Button></div></Panel><Panel title="Transfer Register"><Table rows={transfers} columns={[{key:'transfer_no',label:'No'},{key:'transfer_date',label:'Date'},{key:'from_account_name',label:'From'},{key:'to_account_name',label:'To'},{key:'amount',label:'Amount',render:r=>money(r.amount)}]}/></Panel></div>}

    {active === 'due' && <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Customer Collection / Supplier Payment" description="Posts party ledger and cash/bank ledger together."><div className="grid gap-3 sm:grid-cols-2"><Input label="Date" type="date" value={due.payment_date} onChange={e=>setDue({...due,payment_date:e.target.value})}/><Select label="Direction" value={due.payment_direction} onChange={e=>setDue({...due,payment_direction:e.target.value})}><option value="customer_collection">Customer Collection</option><option value="supplier_payment">Supplier Payment</option><option value="refund">Refund</option><option value="adjustment">Adjustment</option></Select><Select label="Party Type" value={due.party_type} onChange={e=>setDue({...due,party_type:e.target.value})}><option value="customer">Customer</option><option value="supplier">Supplier</option><option value="other">Other</option></Select><Input label="Party ID" value={due.party_id} onChange={e=>setDue({...due,party_id:e.target.value})}/><Select label="Receivable/Payable Account" value={due.account_id} onChange={e=>setDue({...due,account_id:e.target.value})}><option value="">Select</option>{[...assetAccounts, ...liabilityAccounts].map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Select label="Cash/Bank Account" value={due.cash_bank_account_id} onChange={e=>setDue({...due,cash_bank_account_id:e.target.value})}><option value="">Select</option>{cashAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Input label="Amount" type="number" value={due.amount} onChange={e=>setDue({...due,amount:e.target.value})}/><Input label="Reference" value={due.reference_no} onChange={e=>setDue({...due,reference_no:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Note" value={due.note} onChange={e=>setDue({...due,note:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveDue}><HandCoins size={16}/>Post Due Transaction</Button></div></Panel><Panel title="Due Payment Register"><Table rows={duePayments} columns={[{key:'payment_no',label:'No'},{key:'payment_date',label:'Date'},{key:'payment_direction',label:'Direction'},{key:'party_type',label:'Party'},{key:'amount',label:'Amount',render:r=>money(r.amount)}]}/></Panel></div>}

    {active === 'cash' && <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Open / Submit Cash Session" description="Opening and counted closing are persisted. Variance is calculated from posted cashbook entries."><div className="grid gap-3 sm:grid-cols-2"><Select label="Branch" value={cash.branch_id} onChange={e=>setCash({...cash,branch_id:e.target.value})}><option value="">All / none</option>{(refs.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Cash Account" value={cash.cash_account_id} onChange={e=>setCash({...cash,cash_account_id:e.target.value})}><option value="">Default cash</option>{cashAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Input label="Opening Amount" type="number" value={cash.opening_amount} onChange={e=>setCash({...cash,opening_amount:e.target.value})}/><Input label="Counted Closing" type="number" value={cash.counted_closing_amount} onChange={e=>setCash({...cash,counted_closing_amount:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Note" value={cash.note} onChange={e=>setCash({...cash,note:e.target.value})}/></div></div><div className="mt-4 flex flex-wrap gap-2"><Button busy={saving} onClick={openCash}><Plus size={16}/>Open Session</Button>{cashSessions.filter(x=>x.status==='open').slice(0,1).map(x=><Button key={x.id} tone="soft" busy={saving} onClick={()=>closeCash(x.id)}><Save size={16}/>Submit Open Session</Button>)}</div></Panel><Panel title="Cash Sessions"><Table rows={cashSessions} columns={[{key:'session_no',label:'No'},{key:'cashier_name',label:'Cashier'},{key:'opening_amount',label:'Opening',render:r=>money(r.opening_amount)},{key:'system_closing_amount',label:'System',render:r=>money(r.system_closing_amount)},{key:'variance_amount',label:'Variance',render:r=>money(r.variance_amount)},{key:'status',label:'Status'}]}/></Panel></div>}

    {active === 'recon' && <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel title="Gateway / COD Reconciliation" description="Records provider amount, internal reference and variance state."><div className="grid gap-3 sm:grid-cols-2"><Input label="Provider" value={recon.provider} onChange={e=>setRecon({...recon,provider:e.target.value})}/><Input label="Channel" value={recon.channel} onChange={e=>setRecon({...recon,channel:e.target.value})}/><Input label="External Ref" value={recon.external_reference} onChange={e=>setRecon({...recon,external_reference:e.target.value})}/><Input label="Internal Ref" value={recon.internal_reference} onChange={e=>setRecon({...recon,internal_reference:e.target.value})}/><Input label="Expected" type="number" value={recon.expected_amount} onChange={e=>setRecon({...recon,expected_amount:e.target.value})}/><Input label="Received" type="number" value={recon.received_amount} onChange={e=>setRecon({...recon,received_amount:e.target.value})}/><Select label="Status" value={recon.status} onChange={e=>setRecon({...recon,status:e.target.value})}><option value="pending">Pending</option><option value="matched">Matched</option><option value="variance">Variance</option><option value="unidentified">Unidentified</option><option value="rejected">Rejected</option></Select><Select label="Branch" value={recon.branch_id} onChange={e=>setRecon({...recon,branch_id:e.target.value})}><option value="">All / none</option>{(refs.branches||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><div className="sm:col-span-2"><Textarea label="Note" value={recon.note} onChange={e=>setRecon({...recon,note:e.target.value})}/></div></div><div className="mt-4"><Button busy={saving} onClick={saveRecon}><ShieldCheck size={16}/>Save Reconciliation</Button></div></Panel><Panel title="Reconciliation Queue"><Table rows={reconciliations} columns={[{key:'provider',label:'Provider'},{key:'channel',label:'Channel'},{key:'expected_amount',label:'Expected',render:r=>money(r.expected_amount)},{key:'received_amount',label:'Received',render:r=>money(r.received_amount)},{key:'variance_amount',label:'Variance',render:r=>money(r.variance_amount)},{key:'status',label:'Status'}]}/></Panel></div>}

    {active === 'reports' && <div className="space-y-5"><Panel title="Financial Statements" description="Calculated from posted ledger lines only." action={<Button tone="soft" onClick={downloadReport}><Download size={16}/>Export CSV</Button>}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Trial Debit" value={money(trial.total_debit)} icon={BookOpenCheck}/><Metric label="Trial Credit" value={money(trial.total_credit)} icon={BookOpenCheck}/><Metric label="Income" value={money(pnl.income)} icon={Banknote}/><Metric label="Expense" value={money(pnl.expense)} icon={WalletCards}/><Metric label="Net Profit" value={money(pnl.net_profit)} icon={Landmark}/></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><Metric label="Assets" value={money(sheet.assets)} icon={Landmark}/><Metric label="Liability" value={money(sheet.liabilities)} icon={Banknote}/><Metric label="Equity" value={money(sheet.equity)} icon={ShieldCheck}/></div></Panel><Panel title="Trial Balance Rows"><Table rows={trial.rows || []} columns={[{key:'code',label:'Code'},{key:'account',label:'Account'},{key:'type',label:'Type'},{key:'debit',label:'Debit',render:r=>money(r.debit)},{key:'credit',label:'Credit',render:r=>money(r.credit)}]}/></Panel></div>}

    {active === 'audit' && <div className="space-y-5"><Panel title="Finance Operation History" description="Every finance operation writes a finance-specific audit/history entry."><Table rows={audit} columns={[{key:'action',label:'Action'},{key:'resource_type',label:'Resource'},{key:'resource_id',label:'ID'},{key:'user_name',label:'User'},{key:'created_at',label:'Time'}]}/></Panel><Panel title="Acceptance Status"><div className="grid gap-3 md:grid-cols-2">{Object.entries(acceptance.tables || {}).map(([k,v])=><div key={k} className="flex items-center justify-between rounded-xl border border-[var(--nst-dashboard-border)] px-4 py-3"><span className="text-sm font-bold">{k}</span><span className={v?'text-emerald-500':'text-red-500'}>{v?'READY':'MISSING'}</span></div>)}</div></Panel></div>}
  </div>;
}
