<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\{AppCenterApp,AppCenterRelease,ApkBuildRequest};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Storage};
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class AppCenterController extends Controller
{
    public function publicIndex(){ $apps=AppCenterApp::query()->where('is_active',1)->with(['publishedRelease'])->orderByDesc('is_featured')->latest()->get()->filter(fn($a)=>$a->publishedRelease)->values(); return response()->json(['status'=>true,'data'=>$apps]); }
    public function publicShow(string $slug){$app=AppCenterApp::where('slug',$slug)->where('is_active',1)->with(['releases'=>fn($q)=>$q->where('status','published')->orderByDesc('version_code')])->firstOrFail();return response()->json(['status'=>true,'data'=>$app]);}
    public function download(int $release){$r=AppCenterRelease::where('status','published')->findOrFail($release);abort_unless($r->apk_path&&Storage::disk('local')->exists($r->apk_path),404);$r->app()->increment('downloads');return Storage::disk('local')->download($r->apk_path,Str::slug($r->app->name).'-'.$r->version_name.'.apk',['Content-Type'=>'application/vnd.android.package-archive','X-Content-Type-Options'=>'nosniff']);}
    public function index(){return response()->json(['status'=>true,'data'=>AppCenterApp::with(['releases'=>fn($q)=>$q->orderByDesc('version_code')])->latest()->get()]);}
    public function store(Request $r){$d=$r->validate(['name'=>'required|string|max:120','slug'=>'nullable|string|max:140','package_name'=>'required|regex:/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/|unique:app_center_apps,package_name','category'=>'nullable|string|max:100','developer'=>'nullable|string|max:120','short_description'=>'nullable|string|max:500','description'=>'nullable|string','play_store_url'=>'nullable|url','website_url'=>'required|url','rating'=>'nullable|numeric|min:0|max:5','is_featured'=>'boolean','is_active'=>'boolean']);$d['slug']=Str::slug($d['slug']??$d['name']);$d['created_by']=$r->user()?->id;return response()->json(['status'=>true,'data'=>AppCenterApp::create($d)],201);}
    public function update(Request $r,int $id){$a=AppCenterApp::findOrFail($id);$d=$r->validate(['name'=>'sometimes|required|string|max:120','slug'=>'sometimes|string|max:140','package_name'=>['sometimes','required','regex:/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/',Rule::unique('app_center_apps','package_name')->ignore($a->id)],'category'=>'nullable|string|max:100','developer'=>'nullable|string|max:120','short_description'=>'nullable|string|max:500','description'=>'nullable|string','play_store_url'=>'nullable|url','website_url'=>'sometimes|required|url','rating'=>'nullable|numeric|min:0|max:5','is_featured'=>'boolean','is_active'=>'boolean']);if(isset($d['slug']))$d['slug']=Str::slug($d['slug']);$a->update($d);return response()->json(['status'=>true,'data'=>$a->fresh('releases')]);}
    public function destroy(int $id){$a=AppCenterApp::with('releases')->findOrFail($id);foreach($a->releases as $x){foreach(array_filter([$x->apk_path,$x->aab_path]) as $p)Storage::disk('local')->delete($p);}$a->delete();return response()->json(['status'=>true]);}
    public function uploadRelease(Request $r,int $app){$a=AppCenterApp::findOrFail($app);$d=$r->validate(['apk'=>'nullable|file|max:512000','aab'=>'nullable|file|max:512000','version_name'=>'required|regex:/^\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.-]+)?$/','version_code'=>'required|integer|min:1','min_android'=>'required|integer|min:26|max:36','target_android'=>'nullable|integer|min:26|max:36','changelog'=>'nullable|string','scan_status'=>'nullable|in:pending,clean,warning,blocked','scan_notes'=>'nullable|string']);abort_unless($r->hasFile('apk')||$r->hasFile('aab'),422,'APK or AAB is required.');$values=['app_id'=>$a->id,'version_name'=>$d['version_name'],'version_code'=>$d['version_code'],'min_android'=>$d['min_android'],'target_android'=>$d['target_android']??null,'changelog'=>$d['changelog']??null,'scan_status'=>$d['scan_status']??'pending','scan_notes'=>$d['scan_notes']??null,'created_by'=>$r->user()?->id];foreach(['apk','aab'] as $kind){if(!$r->hasFile($kind))continue;$f=$r->file($kind);abort_unless(strtolower($f->getClientOriginalExtension())===$kind,422,'Invalid '.$kind.' file.');$path=$f->store('private/app-center/'.$a->id,'local');$full=Storage::disk('local')->path($path);$values[$kind.'_path']=$path;if($kind==='apk'){$values['file_size']=filesize($full);$values['sha256']=hash_file('sha256',$full);$values['md5']=hash_file('md5',$full);}}$rel=AppCenterRelease::create($values);return response()->json(['status'=>true,'data'=>$rel],201);}
    public function releaseStatus(Request $r,int $id){$rel=AppCenterRelease::findOrFail($id);$d=$r->validate(['status'=>'required|in:draft,published,archived','scan_status'=>'nullable|in:pending,clean,warning,blocked','scan_notes'=>'nullable|string']);if($d['status']==='published'){abort_if(($d['scan_status']??$rel->scan_status)==='blocked',422,'Blocked release cannot be published.');AppCenterRelease::where('app_id',$rel->app_id)->whereKeyNot($rel->id)->where('status','published')->update(['status'=>'archived']);$d['published_at']=now();}$rel->update($d);return response()->json(['status'=>true,'data'=>$rel]);}
    public function createBuild(Request $r){$d=$r->validate(['app_id'=>'required|exists:app_center_apps,id','app_name'=>'required|string|max:120','package_name'=>'required|regex:/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/','website_url'=>'required|url','version_name'=>'required|regex:/^\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.-]+)?$/','version_code'=>'required|integer|min:1','min_android'=>'required|integer|min:26|max:36','target_android'=>'required|integer|min:26|max:36','theme_color'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','orientation'=>'required|in:portrait,landscape,any','build_targets'=>'required|array|min:1','build_targets.*'=>'in:apk,aab']);$app=AppCenterApp::findOrFail($d['app_id']);abort_unless($app->package_name===$d['package_name'],422,'Package name does not match the selected app.');abort_if(AppCenterRelease::where('app_id',$app->id)->where('version_code',$d['version_code'])->exists(),422,'Version code already exists.');$d['build_targets']=array_values(array_unique($d['build_targets']));$b=ApkBuildRequest::create(['app_id'=>$app->id,'build_token'=>(string)Str::uuid(),'status'=>'queued','configuration'=>$d,'requested_by'=>$r->user()?->id]);return response()->json(['status'=>true,'message'=>'Production build queued.','data'=>$b],201);}
    public function builds(){return response()->json(['status'=>true,'data'=>ApkBuildRequest::with('app')->latest()->limit(100)->get()]);}
    public function workerFetch(Request $r){$r->validate(['worker_secret'=>'required|string','worker_id'=>'required|string|max:120']);abort_unless(hash_equals((string)config('services.apk_builder.secret'),(string)$r->worker_secret),403);$b=DB::transaction(function()use($r){$b=ApkBuildRequest::where('status','queued')->orderBy('id')->lockForUpdate()->first();if(!$b)return null;$b->update(['status'=>'building','worker_id'=>$r->worker_id,'started_at'=>now(),'error_message'=>null]);return $b->fresh();},3);return response()->json(['status'=>true,'data'=>$b]);}
    public function workerComplete(Request $r,string $token){$this->authoriseWorker($r);$b=ApkBuildRequest::where('build_token',$token)->where('status','building')->firstOrFail();$r->validate(['apk'=>'nullable|file|max:512000','aab'=>'nullable|file|max:512000','build_log'=>'nullable|string','worker_id'=>'required|string']);abort_unless($r->hasFile('apk')||$r->hasFile('aab'),422,'No build artifact uploaded.');abort_unless(!$b->worker_id||hash_equals((string)$b->worker_id,(string)$r->worker_id),409,'Worker mismatch.');$updates=['status'=>'completed','build_log'=>$r->input('build_log'),'finished_at'=>now()];$release=['app_id'=>$b->app_id,'version_name'=>$b->configuration['version_name'],'version_code'=>$b->configuration['version_code'],'min_android'=>$b->configuration['min_android'],'target_android'=>$b->configuration['target_android'],'status'=>'draft','scan_status'=>'pending','created_by'=>$b->requested_by];foreach(['apk','aab'] as $kind){if(!$r->hasFile($kind))continue;$f=$r->file($kind);abort_unless(strtolower($f->getClientOriginalExtension())===$kind,422,'Invalid artifact extension.');$path=$f->store('private/apk-builds/'.$b->app_id,'local');$full=Storage::disk('local')->path($path);$updates[$kind.'_path']=$path;$release[$kind.'_path']=$path;if($kind==='apk'){$updates['artifact_path']=$path;$updates['file_size']=filesize($full);$updates['sha256']=hash_file('sha256',$full);$updates['md5']=hash_file('md5',$full);$release['file_size']=$updates['file_size'];$release['sha256']=$updates['sha256'];$release['md5']=$updates['md5'];}}DB::transaction(function()use($b,$updates,$release){$b->update($updates);AppCenterRelease::updateOrCreate(['app_id'=>$release['app_id'],'version_code'=>$release['version_code']],$release);});return response()->json(['status'=>true]);}
    public function workerFail(Request $r,string $token){$this->authoriseWorker($r);$d=$r->validate(['worker_id'=>'required|string','error_message'=>'required|string|max:10000','build_log'=>'nullable|string']);$b=ApkBuildRequest::where('build_token',$token)->firstOrFail();abort_unless(!$b->worker_id||hash_equals((string)$b->worker_id,(string)$d['worker_id']),409,'Worker mismatch.');$b->update(['status'=>'failed','error_message'=>$d['error_message'],'build_log'=>$d['build_log']??$b->build_log,'finished_at'=>now()]);return response()->json(['status'=>true]);}
    private function authoriseWorker(Request $r):void{abort_unless(hash_equals((string)config('services.apk_builder.secret'),(string)$r->input('worker_secret')),403);}
}
